name: Build and Deploy Code

on: [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v7
      - name: say hi to devante
        run: echo "hello devante"
